# Generated by Django 5.1.5 on 2025-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_cat_tbl_subcategory_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=30)),
                ('lawyer_email', models.CharField(max_length=30)),
                ('lawyer_contact', models.CharField(max_length=10)),
                ('lawyer_address', models.CharField(max_length=100)),
                ('lawyer_photo', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('lawyer_proof', models.FileField(upload_to='Assets/Admin/Photo/')),
                ('lawyer_password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_case',
        ),
    ]
