# Generated by Django 5.1.5 on 2025-01-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_lawyer_delete_tbl_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_email', models.CharField(max_length=30)),
                ('parent_contact', models.CharField(max_length=10)),
                ('parent_address', models.CharField(max_length=100)),
                ('parent_photo', models.FileField(upload_to='Assets/Admin/Photo')),
                ('parent_proof', models.FileField(upload_to='Assets/Admin/Proof')),
                ('parent_password', models.CharField(max_length=15)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_lawyer')),
            ],
        ),
    ]
