# Generated by Django 5.1.5 on 2025-01-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_juvenile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_name', models.CharField(max_length=30)),
                ('juvenile_age', models.CharField(max_length=2)),
                ('juvenile_gender', models.CharField(max_length=10)),
                ('juvenile_height', models.CharField(max_length=10)),
                ('juvenile_weight', models.CharField(max_length=10)),
                ('juvenile_address', models.CharField(max_length=100)),
                ('juvenile_photo', models.FileField(upload_to='Assets/Admin/Photo')),
                ('juvenile_proof', models.FileField(upload_to='Assets/Admin/Proof')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_lawyer')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_parent')),
            ],
        ),
    ]
