# Generated by Django 5.1.5 on 2025-01-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_juvenile',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='tbl_juvenile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tbl_parent',
            name='lawyer',
        ),
        migrations.AddField(
            model_name='tbl_parent',
            name='parent_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_parent',
            name='parent_contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='tbl_parent',
            name='parent_photo',
            field=models.FileField(upload_to='Assets/Parent/Photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_parent',
            name='parent_proof',
            field=models.FileField(upload_to='Assets/Parent/Proof/'),
        ),
        migrations.DeleteModel(
            name='tbl_case',
        ),
        migrations.DeleteModel(
            name='tbl_juvenile',
        ),
    ]
