# Generated by Django 5.1.5 on 2025-01-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_juvenile_tbl_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_parent',
        ),
    ]
