# Generated by Django 5.1.5 on 2025-02-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_juvenile_tbl_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_juvenile',
            name='parent',
        ),
    ]
