# Generated by Django 5.1.5 on 2025-02-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_tbl_juvenile_tbl_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_case',
            name='lawyer',
        ),
        migrations.AlterField(
            model_name='tbl_case',
            name='case_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
