# Generated by Django 5.1.5 on 2025-02-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_tbl_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_date', models.DateField()),
                ('fees_amount', models.CharField(max_length=10)),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
