# Generated by Django 5.1.5 on 2025-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_tbl_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_healthstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthstaff_name', models.CharField(max_length=30)),
                ('healthstaff_email', models.EmailField(max_length=254)),
                ('healthstaff_contact', models.CharField(max_length=11)),
                ('healthstaff_password', models.CharField(max_length=30)),
            ],
        ),
    ]
