# Generated by Django 5.1.5 on 2025-02-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_healthreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rehabilitationstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehabilitationstaff_name', models.CharField(max_length=30)),
                ('rehabilitationstaff_email', models.EmailField(max_length=254)),
                ('rehabilitationstaff_contact', models.CharField(max_length=11)),
                ('rehabilitationstaff_password', models.CharField(max_length=30)),
            ],
        ),
    ]
