# Generated by Django 5.1.5 on 2025-02-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_tbl_educationalstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rehabilitationreport',
            name='rehabilitation_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rehabilitationstaff'),
        ),
        migrations.CreateModel(
            name='tbl_educationalreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationalreport_date', models.DateField(auto_now_add=True)),
                ('educationalreport_details', models.CharField(max_length=200)),
                ('educational_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_healthstaff')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
