# Generated by Django 5.1.5 on 2025-02-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_alter_tbl_rehabilitationreport_rehabilitation_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_educationalreport',
            name='educational_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_educationalstaff'),
        ),
    ]
