# Generated by Django 5.1.5 on 2025-02-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_alter_tbl_educationalreport_educational_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_educationalreport',
        ),
    ]
