# Generated by Django 5.1.5 on 2025-02-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_delete_tbl_educationalreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_healthreport',
        ),
    ]
