# Generated by Django 5.1.5 on 2025-02-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_delete_tbl_healthreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rehabilitationreport',
        ),
    ]
