# Generated by Django 5.1.5 on 2025-02-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0036_alter_tbl_juvenile_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_appointment',
        ),
    ]
