# Generated by Django 5.1.5 on 2025-02-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0039_remove_tbl_juvenile_lawyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_email', models.CharField(max_length=30)),
                ('parent_contact', models.CharField(max_length=13)),
                ('parent_address', models.CharField(max_length=100)),
                ('parent_photo', models.FileField(upload_to='Assets/Parent/Photo/')),
                ('parent_proof', models.FileField(upload_to='Assets/Parent/Proof/')),
                ('parent_password', models.CharField(max_length=15)),
                ('parent_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_juvenile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_name', models.CharField(max_length=30)),
                ('juvenile_age', models.CharField(max_length=2)),
                ('juvenile_gender', models.CharField(max_length=10)),
                ('juvenile_height', models.CharField(max_length=10)),
                ('juvenile_weight', models.CharField(max_length=10)),
                ('juvenile_address', models.CharField(max_length=100)),
                ('juvenile_photo', models.FileField(upload_to='Assets/Admin/Photo')),
                ('juvenile_proof', models.FileField(upload_to='Assets/Admin/Proof')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_lawyer')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_parent')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30)),
                ('case_details', models.CharField(max_length=100)),
                ('case_date', models.DateField(auto_now_add=True)),
                ('casetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_casetype')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
