# Generated by Django 5.1.5 on 2025-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_tbl_parent_tbl_juvenile_tbl_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_juvenile',
            name='juvenile_admissiondate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_juvenile',
            name='juvenile_dob',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='tbl_case',
        ),
    ]
