# Generated by Django 5.1.5 on 2025-02-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_tbl_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignedustf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationalstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_educationalstaff')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignhltstf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_healthstaff')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignrehabstf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
                ('rehabilitationstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rehabilitationstaff')),
            ],
        ),
    ]
