# Generated by Django 5.1.6 on 2025-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0043_tbl_assignedustf_tbl_assignhltstf_tbl_assignrehabstf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_educationalstaff',
            name='ed_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_healthstaff',
            name='hlt_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_rehabilitationstaff',
            name='rehab_status',
            field=models.IntegerField(default=0),
        ),
    ]
