# Generated by Django 5.1.5 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthStaff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_healthreport',
        ),
    ]
