# Generated by Django 5.1.5 on 2025-02-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0040_tbl_parent_tbl_juvenile_tbl_case'),
        ('HealthStaff', '0002_delete_tbl_healthreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_healthreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthreport_date', models.DateField(auto_now_add=True)),
                ('healthreport_details', models.CharField(max_length=200)),
                ('health_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_healthstaff')),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
