# Generated by Django 5.1.5 on 2025-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthStaff', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_healthreport',
        ),
    ]
