# Generated by Django 5.1.5 on 2025-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0003_tbl_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
