# Generated by Django 5.1.5 on 2025-02-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0005_alter_tbl_appointment_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_appointment',
        ),
    ]
