# Generated by Django 5.1.5 on 2025-02-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0037_delete_tbl_appointment'),
        ('Parent', '0006_delete_tbl_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_details', models.CharField(max_length=250)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.IntegerField(default=0)),
                ('appointment_fordate', models.DateField()),
                ('appointment_fortime', models.TimeField()),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
