# Generated by Django 5.1.5 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0007_tbl_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='parent',
        ),
        migrations.DeleteModel(
            name='tbl_appointment',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
