# Generated by Django 5.1.5 on 2025-02-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0040_tbl_parent_tbl_juvenile_tbl_case'),
        ('Parent', '0008_remove_tbl_complaint_parent_delete_tbl_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_details', models.CharField(max_length=250)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appointment_status', models.IntegerField(default=0)),
                ('appointment_fordate', models.DateField()),
                ('appointment_fortime', models.TimeField()),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_content', models.CharField(max_length=100)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_reply', models.CharField(default='Not Yet Replyed', max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_parent')),
            ],
        ),
    ]
