# Generated by Django 5.1.5 on 2025-02-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hearing',
        ),
    ]
