# Generated by Django 5.1.5 on 2025-02-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hearing',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
