# Generated by Django 5.1.5 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyer', '0004_alter_tbl_hearing_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hearing',
        ),
    ]
