# Generated by Django 5.1.5 on 2025-02-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0040_tbl_parent_tbl_juvenile_tbl_case'),
        ('Lawyer', '0005_delete_tbl_hearing'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('hearing_status', models.IntegerField(default=0)),
                ('juvenile_fordate', models.DateField()),
                ('amount', models.CharField(max_length=50)),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_juvenile')),
            ],
        ),
    ]
