# Generated by Django 5.1.5 on 2025-01-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_email', models.CharField(max_length=30)),
                ('parent_contact', models.CharField(max_length=13)),
                ('parent_address', models.CharField(max_length=100)),
                ('parent_photo', models.FileField(upload_to='Assets/Parent/Photo/')),
                ('parent_proof', models.FileField(upload_to='Assets/Parent/Proof/')),
                ('parent_password', models.CharField(max_length=15)),
                ('parent_status', models.IntegerField(default=0)),
            ],
        ),
    ]
